### ISSUE TITLE
Interact with contracts

### ISSUE THREAD

**Issue by rynobey** [rynobey/QuorumNetworkTester#7]
Add functions that can be used to interact with contracts. Also add functionality for conveniently working with contracts for benchmarking setups.

**Comment by rynobey** [comment]
1) Design a "benchmarking" contract with:
>- function(s) for doing a specified number of state variable updates (perhaps also different state variable types?). The number of updates should be given as an input parameter - this allows for an adjustable gas usage per transaction (gas usage information is not currently available in Quorum, since the pricing has been removed, although transactions will still fail if not enough gas is provided...). 
>- (function(s) for doing a specified number of iterations of a computation, for same reason as above.)
2) Write code for compiling and deploying contracts directly through web3 (could also use truffle...)
3) Write code for interacting with the deployed contracts
4) Also think about the following:
>- Ability to deploy and interact with multiple instances of the same "benchmarking" contract.
>- Ability for multiple external accounts to interact with a "benchmarking" contract simultaneously.
>- Compare N contracts with 1 state update each (each instance has own storage) with N state updates on 1 contract

Thoughts @coeniebeyers ?

**Comment by rynobey** [comment]
For now, start with standard ERC20 contract.

**Comment by coeniebeyers** [comment]
Sounds good!

**Comment by rynobey** [comment]
Can now deploy and interacts with instances of ERC20 contracts! Code not pretty yet, but it works...
